apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2024-05-15T16:20:18Z","labels":{"app":"spring-petclinic-rest"},"name":"spring-petclinic-rest","namespace":"default","resourceVersion":"3993","uid":"be43fdf6-4108-4abd-a1b9-6bf017964c58"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"10.99.125.30","clusterIPs":["10.99.125.30"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":30155,"port":9966,"protocol":"TCP","targetPort":9966}],"selector":{"app":"spring-petclinic-rest"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2024-05-15T18:09:35Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "500"
  uid: 3f2edd59-8c27-4381-b1de-595dab73240d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.125.30
  clusterIPs:
  - 10.99.125.30
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30155
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
